### ISSUE TITLE
有没有公开的测试环境，我也编一个试试看：）

### ISSUE THREAD

**Issue by liuyubobobo** [halfrost/threes-ai#14]

**Comment by halfrost** [comment]
老师应该说的就是我微信朋友圈发的那个前端页面对吧。。这个应该可以。。。不过今天回家了。。这几天过年估计没时间上网。。我应该可以打一个 docker 镜像出来。。然后老师写逻辑就好了。。我会把每回合的棋盘的二维数组和下一步会出现的砖块的数字都发过来。。程序根据这两个入参返回给我移动的4个方向之一即可。

**Comment by liuyubobobo** [comment]
啊哦，这么麻烦就算啦。我以为是公共的比赛，有公开的环境：）
